# Site settings
title: Introducci贸n a la Programaci贸n
header-img: img/home-bg.jpg
description: "Este el sitio de la materia Introducci贸n a la Programaci贸n"
baseurl: ""
url: "http://inpr-sarmiento.github.io/"
github_username: "inpr-sarmiento"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jemoji]
